local CommonConfig = {
    config = {
        preservePunctuation = true
    },
    matrices = {
        consonants = {
            "B", "C", "D", "F", "G", "H", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y", "Z",
            "Bl", "Br", "Ch", "Cl", "Cr", "Dr", "Dw", "Fl", "Fr", "Gh", "Gl", "Gr", "Kn", "Ph", "Pl", "Pr",
            "Sc", "Sh", "Sk", "Sl", "Sm", "Sn", "Sp", "Sq", "St", "Sw", "Th", "Tr", "Tw", "Wh", "Wr", "Str", "Thr"
        },
        vowels = {
            "a", "e", "i", "o", "u", "y", "ae", "ai", "au", "aw", "ea", "ee", "ei", "eo", "eu", "ey", "ia",
            "ie", "io", "oa", "oe", "oi", "oo", "ou", "ow", "oy", "ua", "ue", "ui"
        },
        endings = {
            "b", "c", "ck", "d", "f", "g", "gh", "k", "l", "ld", "lf", "lk", "lm", "lp", "lt", "m", "n", "nd",
            "ng", "nk", "nt", "p", "r", "rd", "rf", "rk", "rl", "rm", "rn", "rp", "rs", "rt", "s", "sh", "sk",
            "st", "t", "th", "v", "w", "x", "y", "z", ""
        }
    },
    lexicon = {
        verbs = {
            ["attack"]   = { root = "Slean",  tense = "present" },
            ["attacked"] = { root = "Slean",  tense = "past" },
            ["bear"]     = { root = "Beran",  tense = "present" },
            ["bore"]     = { root = "Beran",  tense = "past" },
            ["bind"]     = { root = "Bindan", tense = "present" },
            ["bound"]    = { root = "Bindan", tense = "past" },
            ["break"]    = { root = "Brecan", tense = "present" },
            ["broke"]    = { root = "Brecan", tense = "past" },
            ["bring"]    = { root = "Bring",  tense = "present" },
            ["brought"]  = { root = "Bring",  tense = "past" },
            ["burn"]     = { root = "Brenn",  tense = "present" },
            ["burned"]   = { root = "Brenn",  tense = "past" },
            ["call"]     = { root = "Clyp",   tense = "present" },
            ["called"]   = { root = "Clyp",   tense = "past" },
            ["cleave"]   = { root = "Ceof",   tense = "present" },
            ["cleft"]    = { root = "Ceof",   tense = "past" },
            ["come"]     = { root = "Cuman",  tense = "present" },
            ["came"]     = { root = "Cuman",  tense = "past" },
            ["die"]      = { root = "Sterb",  tense = "present" },
            ["died"]     = { root = "Sterb",  tense = "past" },
            ["drink"]    = { root = "Drinc",  tense = "present" },
            ["drank"]    = { root = "Drinc",  tense = "past" },
            ["fall"]     = { root = "Feall",  tense = "present" },
            ["fell"]     = { root = "Feall",  tense = "past" },
            ["fight"]    = { root = "Feht",   tense = "present" },
            ["fought"]   = { root = "Feht",   tense = "past" },
            ["find"]     = { root = "Findan", tense = "present" },
            ["found"]    = { root = "Findan", tense = "past" },
            ["fly"]      = { root = "Fleog",  tense = "present" },
            ["flew"]     = { root = "Fleog",  tense = "past" },
            ["give"]     = { root = "Giefan", tense = "present" },
            ["gave"]     = { root = "Giefan", tense = "past" },
            ["go"]       = { root = "Gangan", tense = "present" },
            ["went"]     = { root = "Gangan", tense = "past" },
            ["guard"]    = { root = "Ward",   tense = "present" },
            ["guarded"]  = { root = "Ward",   tense = "past" },
            ["heal"]     = { root = "Hael",   tense = "present" },
            ["healed"]   = { root = "Hael",   tense = "past" },
            ["hear"]     = { root = "Hyran",  tense = "present" },
            ["heard"]    = { root = "Hyran",  tense = "past" },
            ["hold"]     = { root = "Heald",  tense = "present" },
            ["held"]     = { root = "Heald",  tense = "past" },
            ["kill"]     = { root = "Cwell",  tense = "present" },
            ["killed"]   = { root = "Cwell",  tense = "past" },
            ["know"]     = { root = "Cnawan", tense = "present" },
            ["knew"]     = { root = "Cnawan", tense = "past" },
            ["lead"]     = { root = "Laed",   tense = "present" },
            ["led"]      = { root = "Laed",   tense = "past" },
            ["live"]     = { root = "Lifan",  tense = "present" },
            ["lived"]    = { root = "Lifan",  tense = "past" },
            ["look"]     = { root = "Locan",  tense = "present" },
            ["looked"]   = { root = "Locan",  tense = "past" },
            ["love"]     = { root = "Lufan",  tense = "present" },
            ["loved"]    = { root = "Lufan",  tense = "past" },
            ["make"]     = { root = "Mavian", tense = "present" },
            ["made"]     = { root = "Mavian", tense = "past" },
            ["protect"]  = { root = "Scild",  tense = "present" },
            ["protected"]= { root = "Scild",  tense = "past" },
            ["read"]     = { root = "Rædan",  tense = "present" },
            ["run"]      = { root = "Rinnan", tense = "present" },
            ["ran"]      = { root = "Rinnan", tense = "past" },
            ["see"]      = { root = "Seon",   tense = "present" },
            ["saw"]      = { root = "Seon",   tense = "past" },
            ["seek"]     = { root = "Secan",  tense = "present" },
            ["sought"]   = { root = "Secan",  tense = "past" },
            ["sing"]     = { root = "Singan", tense = "present" },
            ["sang"]     = { root = "Singan", tense = "past" },
            ["slay"]     = { root = "Slean",  tense = "present" },
            ["slew"]     = { root = "Slean",  tense = "past" },
            ["sleep"]    = { root = "Slepan", tense = "present" },
            ["slept"]    = { root = "Slepan", tense = "past" },
            ["speak"]    = { root = "Sprek",  tense = "present" },
            ["spoke"]    = { root = "Sprek",  tense = "past" },
            ["stand"]    = { root = "Standa", tense = "present" },
            ["stood"]    = { root = "Standa", tense = "past" },
            ["strike"]   = { root = "Smitan", tense = "present" },
            ["struck"]   = { root = "Smitan", tense = "past" },
            ["swear"]    = { root = "Sweria", tense = "present" },
            ["swore"]    = { root = "Sweria", tense = "past" },
            ["travel"]   = { root = "Faran",  tense = "present" },
            ["traveled"] = { root = "Faran",  tense = "past" },
            ["walk"]     = { root = "Weal",   tense = "present" },
            ["walked"]   = { root = "Weal",   tense = "past" },
            ["work"]     = { root = "Wyrcan", tense = "present" },
            ["worked"]   = { root = "Wyrcan", tense = "past" }
        },
        nouns = {
            ["alliance"] = { root = "Bandu",   gender = "feminine",  isPlural = false },
            ["armies"]   = { root = "Fyrd",    gender = "feminine",  isPlural = true },
            ["army"]     = { root = "Fyrd",    gender = "feminine",  isPlural = false },
            ["battle"]   = { root = "Beadu",   gender = "feminine",  isPlural = false },
            ["battles"]  = { root = "Beadu",   gender = "feminine",  isPlural = true },
            ["blade"]    = { root = "Mekki",   gender = "masculine", isPlural = false },
            ["blades"]   = { root = "Mekki",   gender = "masculine", isPlural = true },
            ["blood"]    = { root = "Blod",    gender = "neutral",   isPlural = false },
            ["brother"]  = { root = "Brothor", gender = "masculine", isPlural = false },
            ["brothers"] = { root = "Brothor", gender = "masculine", isPlural = true },
            ["castle"]   = { root = "Burg",    gender = "feminine",  isPlural = false },
            ["castles"]  = { root = "Burg",    gender = "feminine",  isPlural = true },
            ["crown"]    = { root = "Cyne",    gender = "feminine",  isPlural = false },
            ["crowns"]   = { root = "Cyne",    gender = "feminine",  isPlural = true },
            ["day"]      = { root = "Dag",     gender = "masculine", isPlural = false },
            ["days"]     = { root = "Dag",     gender = "masculine", isPlural = true },
            ["dragon"]   = { root = "Wyrm",    gender = "masculine", isPlural = false },
            ["dragons"]  = { root = "Wyrm",    gender = "masculine", isPlural = true },
            ["earth"]    = { root = "Eorthe",  gender = "feminine",  isPlural = false },
            ["enemy"]    = { root = "Feond",   gender = "masculine", isPlural = false },
            ["enemies"]  = { root = "Feond",   gender = "masculine", isPlural = true },
            ["father"]   = { root = "Fader",   gender = "masculine", isPlural = false },
            ["fire"]     = { root = "Fyr",     gender = "neutral",   isPlural = false },
            ["friend"]   = { root = "Freond",  gender = "masculine", isPlural = false },
            ["friends"]  = { root = "Freond",  gender = "masculine", isPlural = true },
            ["glory"]    = { root = "Dom",     gender = "masculine", isPlural = false },
            ["god"]      = { root = "God",     gender = "masculine", isPlural = false },
            ["gods"]     = { root = "God",     gender = "masculine", isPlural = true },
            ["gold"]     = { root = "Gold",    gender = "neutral",   isPlural = false },
            ["honor"]    = { root = "Eorl",    gender = "masculine", isPlural = false },
            ["horse"]    = { root = "Hrss",    gender = "neutral",   isPlural = false },
            ["horses"]   = { root = "Hrss",    gender = "neutral",   isPlural = true },
            ["house"]    = { root = "Hus",     gender = "neutral",   isPlural = false },
            ["houses"]   = { root = "Hus",     gender = "neutral",   isPlural = true },
            ["king"]     = { root = "Kuninc",  gender = "masculine", isPlural = false },
            ["kings"]    = { root = "Kuninc",  gender = "masculine", isPlural = true },
            ["knight"]   = { root = "Cniht",   gender = "masculine", isPlural = false },
            ["knights"]  = { root = "Cniht",   gender = "masculine", isPlural = true },
            ["land"]     = { root = "Land",    gender = "neutral",   isPlural = false },
            ["lands"]    = { root = "Land",    gender = "neutral",   isPlural = true },
            ["leader"]   = { root = "Heret",   gender = "masculine", isPlural = false },
            ["life"]     = { root = "Lif",     gender = "neutral",   isPlural = false },
            ["light"]    = { root = "Leoht",   gender = "neutral",   isPlural = false },
            ["lord"]     = { root = "Hlaford", gender = "masculine", isPlural = false },
            ["lords"]    = { root = "Hlaford", gender = "masculine", isPlural = true },
            ["man"]      = { root = "Mann",    gender = "masculine", isPlural = false },
            ["men"]      = { root = "Mann",    gender = "masculine", isPlural = true },
            ["morning"]  = { root = "Morgen",  gender = "neutral",   isPlural = false },
            ["mother"]   = { root = "Modor",   gender = "feminine",  isPlural = false },
            ["night"]    = { root = "Niht",    gender = "feminine",  isPlural = false },
            ["nights"]   = { root = "Niht",    gender = "feminine",  isPlural = true },
            ["oath"]     = { root = "Aeth",    gender = "masculine", isPlural = false },
            ["oaths"]    = { root = "Aeth",    gender = "masculine", isPlural = true },
            ["people"]   = { root = "Folc",    gender = "neutral",   isPlural = true },
            ["queen"]    = { root = "Cwen",    gender = "feminine",  isPlural = false },
            ["queens"]   = { root = "Cwen",    gender = "feminine",  isPlural = true },
            ["realm"]    = { root = "Rike",    gender = "neutral",   isPlural = false },
            ["realms"]   = { root = "Rike",    gender = "neutral",   isPlural = true },
            ["river"]    = { root = "Strom",   gender = "masculine", isPlural = false },
            ["sea"]      = { root = "Saew",    gender = "feminine",  isPlural = false },
            ["shadow"]   = { root = "Scadu",   gender = "feminine",  isPlural = false },
            ["shadows"]  = { root = "Scadu",   gender = "feminine",  isPlural = true },
            ["shield"]   = { root = "Scild",   gender = "masculine", isPlural = false },
            ["shields"]  = { root = "Scild",   gender = "masculine", isPlural = true },
            ["ship"]     = { root = "Scip",    gender = "neutral",   isPlural = false },
            ["ships"]    = { root = "Scip",    gender = "neutral",   isPlural = true },
            ["sister"]   = { root = "Swostor", gender = "feminine",  isPlural = false },
            ["sisters"]  = { root = "Swostor", gender = "feminine",  isPlural = true },
            ["sky"]      = { root = "Heofon",  gender = "masculine", isPlural = false },
            ["soldier"]  = { root = "Saeld",   gender = "masculine", isPlural = false },
            ["soldiers"] = { root = "Saeld",   gender = "masculine", isPlural = true },
            ["son"]      = { root = "Sunu",    gender = "masculine", isPlural = false },
            ["sons"]     = { root = "Sunu",    gender = "masculine", isPlural = true },
            ["soul"]     = { root = "Sawol",   gender = "feminine",  isPlural = false },
            ["souls"]    = { root = "Sawol",   gender = "feminine",  isPlural = true },
            ["spear"]    = { root = "Spaer",   gender = "neutral",   isPlural = false },
            ["spears"]   = { root = "Spaer",   gender = "neutral",   isPlural = true },
            ["star"]     = { root = "Steorra", gender = "masculine", isPlural = false },
            ["stars"]    = { root = "Steorra", gender = "masculine", isPlural = true },
            ["stone"]    = { root = "Stan",    gender = "masculine", isPlural = false },
            ["stones"]   = { root = "Stan",    gender = "masculine", isPlural = true },
            ["storm"]    = { root = "Storm",   gender = "masculine", isPlural = false },
            ["sun"]      = { root = "Sunne",   gender = "feminine",  isPlural = false },
            ["sword"]    = { root = "Sweord",  gender = "neutral",   isPlural = false },
            ["swords"]   = { root = "Sweord",  gender = "neutral",   isPlural = true },
            ["throne"]   = { root = "Selt",    gender = "neutral",   isPlural = false },
            ["town"]     = { root = "Tun",     gender = "masculine", isPlural = false },
            ["towns"]    = { root = "Tun",     gender = "masculine", isPlural = true },
            ["truth"]    = { root = "Soth",    gender = "neutral",   isPlural = false },
            ["victory"]  = { root = "Sige",    gender = "masculine", isPlural = false },
            ["war"]      = { root = "Wig",     gender = "neutral",   isPlural = false },
            ["warrior"]  = { root = "Wiga",    gender = "masculine", isPlural = false },
            ["warriors"] = { root = "Wiga",    gender = "masculine", isPlural = true },
            ["water"]    = { root = "Water",   gender = "neutral",   isPlural = false },
            ["wind"]     = { root = "Wind",    gender = "masculine", isPlural = false },
            ["wolf"]     = { root = "Wulf",    gender = "masculine", isPlural = false },
            ["wolves"]   = { root = "Wulf",    gender = "masculine", isPlural = true },
            ["world"]    = { root = "Weorold", gender = "feminine",  isPlural = false }
        },
        fallbacks = {
            short = {
                "Ash", "Bor", "Bur", "Dag", "Eft", "Far", "Fol", "Gol", "Ham", "Hir",
                "Hof", "Lio", "Lon", "Man", "Mod", "Nud", "Rad", "Ras", "Sun", "Ver",
                "Vil", "Vos", "Weg", "Bora", "Burg", "Dorn", "Fast", "Folc", "Fuld", "Gald",
                "Goth", "Heim", "Lars", "Noth", "Nuff", "Odes", "Riff", "Ruff", "Thor", "Uden",
                "Uhta", "Veld", "Vohl", "Vrum", "Wand"
            },
            medium = {
                "Ador", "Agol", "Algos", "Barad", "Beraht", "Borne", "Bregan", "Dagas", "Dagana",
                "Dana", "Daegil", "Danieb", "Ealdor", "Engoth", "Ergin", "Eynes", "Fahron", "Faran",
                "Garde", "Gedref", "Gelan", "Gisold", "Gloin", "Goibon", "Haldan", "Haldar", "Kuninc", "Majis",
                "Mandos", "Melka", "Meteo", "Morgen", "Nagan", "Nevren", "Novas", "Oldor", "Oldora", "Regen",
                "Regnar", "Rikan", "Rogesh", "Rothas", "Ruftos", "Seldor", "Sidhu", "Skilde", "Tiras", "Valesh",
                "Vandar", "Waldir", "Wandil", "Wela", "Wirsh"
            },
            long = {
                "Aelgestron", "Aetwinter", "Agolandovis", "Aldonoth", "Andovis", "Berahtold", "Berahtolder", "Bornevalesh",
                "Cynegold", "Cynewalden", "Danagarde", "Danavandar", "Dornevalesh", "Dyrstigost", "Ealdorman", "Ealdormanor",
                "Eloderung", "Endirvis", "Ewiddan", "Faergas", "Falhedring", "Farlandowar", "Faranolder", "Firalaine",
                "Forthasador", "Forthis", "Galandoril", "Gloinador", "Gothalgos", "Hamerung", "Hlafordman", "Kaelsig",
                "Koshvel", "Landowar", "Lithtos", "Lordaere", "Methrine", "Morgenland", "Nandige", "Nostyec",
                "Novaedi", "Oldorandor", "Regenthor", "Ruftvess", "Sturume", "Thorlithtos", "Thorniss", "Udenmajis",
                "Vandarwos", "Vassildabor", "Vassildador", "Vastrungen", "Veldbarad", "Wandilolder", "Wershaesire"
            }
        }
    },
    grammar = {
        tensePrefixes = {
            ["present"]    = "",
            ["past"]       = "ge-",
            ["future"]     = "wil-",
            ["imperative"] = "do-"
        },
        personSuffixes = {
            [1] = "e",   -- 1st Person Singular
            [2] = "est", -- 2nd Person Singular
            [3] = "eth", -- 3rd Person Singular
            [4] = "en",  -- 1st Person Plural
            [5] = "ath"  -- 3rd Person Plural
        }
    }
}

local addonName, addon = ...
local Engine = addon.AlgorithmEngine
local Hasher = {}
function Hasher.ProcessText(text)
    return Engine.ProcessText(text, CommonConfig)
end
addon.CommonHasher = Hasher
_G.CommonHasher = Hasher
return Hasher